export enum Action {
    LOAD_DATA = 'LOAD_DATA',
    SET_CARD = 'SET_CARD',
    SET_STATUSES = 'SET_STATUSES',
    SET_SEARCHFILTER = 'SET_SEARCH',
    SET_EPICFILTER = 'SET_EPICFILTER',
    SET_ASSIGNEEFILTER = 'SET_ASSIGNEEFILTER',
    SET_LOADER = 'SET_LOADER',
    CLEAR_FILER = 'CLEAR_FILER'
}
